### ISSUE TITLE
Release `0.2.0`

### ISSUE THREAD

**Issue by corbanvilla** [owlprotocol/contracts#225]
Additional contracts ready for production use, along with some improvement of life issues and documentation clarification.

- [x] #221
- [x] #222 
- [ ] #224 
- [ ] Update subpackage `package.json` values!
- [ ] Publish to npm `0.2.0`
- [ ] Update git-pages or #218 
- [ ] Update contracts or #220 
- [ ] Update Types or #223 
- [ ] Merge into master. 
  - Requires some specific rebases. Ask @corbanvilla or @HrikB 
- [x] OpenGSN integration #270 
- [x] OpenGSN test compatibility #280
